export const FETCH_ORGANISATION = "FETCH_ORGANISATION";
export const FETCH_ORGANISATION_FAIL = "FETCH_ORGANISATION_FAIL";
export const FETCH_ORGANISATION_SUCCESS = "FETCH_ORGANISATION_SUCCESS";
export const FETCH_ORGANISATIONS = "FETCH_ORGANISATIONS";
export const FETCH_ORGANISATIONS_FAIL = "FETCH_ORGANISATIONS_FAIL";
export const FETCH_ORGANISATIONS_SUCCESS = "FETCH_ORGANISATIONS_SUCCESS";
export const FETCH_ORGANISATION_MEMBERS = "FETCH_ORGANISATION_MEMBERS";
export const FETCH_ORGANISATION_MEMBERS_FAIL =
  "FETCH_ORGANISATION_MEMBERS_FAIL";
export const FETCH_ORGANISATION_MEMBERS_SUCCESS =
  "FETCH_ORGANISATION_MEMBERS_SUCCESS";
